name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build for multiple platforms
      run: |
        mkdir -p dist
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/glance-china-linux-amd64 ./cmd/glance-china
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o dist/glance-china-linux-arm64 ./cmd/glance-china
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o dist/glance-china-darwin-amd64 ./cmd/glance-china
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o dist/glance-china-darwin-arm64 ./cmd/glance-china
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o dist/glance-china-windows-amd64.exe ./cmd/glance-china
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
